### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by jayvdb** [unabris/jekyll_constant_values#1]
It would be helpful to explain in the README why this is different from adding a `constants:` key into `_config.yml` and then using `site.constants.foo.bar` in pages.

**Comment by unabris** [comment]
This is not different. This plugin was my first one just to start learning how a Jekyll plugin works. But you are right, I should write on the README file the real purpose

**Comment by unabris** [comment]
You can check the new README.md file [here](https://github.com/unabris/jekyll_constant_values/blob/master/README.md)
